kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: chris-ui-development
  namespace: chris-ui-ci
subjects:
  - kind: ServiceAccount
    name: default
    namespace: chris-ui-development
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:image-puller'