kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: chris-ui
    app.kubernetes.io/part-of: liberty
  name: chris-ui
  namespace: chris-ui-development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chris-ui
  template:
    metadata:
      labels:
        app: chris-ui
    spec:
      containers:
      - name: chris-ui
        image: image-registry.openshift-image-registry.svc:5000/chris-ui-ci/chris-ui-runtime  
        imagePullPolicy: Always
        ports:
        - containerPort: 9080
          name: http
          protocol: TCP