apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesJson6902:
- patch: |-
    - op: replace
      path: /metadata/namespace
      value: myapp-ui-qa
  target:
    kind: Deployment
    name: myapp-ui
- patch: |-
    - op: replace
      path: /metadata/namespace
      value: myapp-ui-qa
  target:
    kind: Service
    name: myapp-ui
- patch: |-
    - op: replace
      path: /metadata/namespace
      value: myapp-ui-qa
  target:
    kind: Route
    name: myapp-ui-route
- patch: |-
    - op: replace
      path: /metadata/name
      value: myapp-ui-qa
  target:
    kind: Namespace
    name: myapp-ui-development
- patch: |-
    - op: replace
      path: /metadata/namespace
      value: myapp-ui-qa
  target:
    kind: RoleBinding
    name: argocd-admin
- patch: |-
    - op: replace
      path: /subjects/0/namespace
      value: myapp-ui-qa
  target:
    kind: RoleBinding
    name: myapp-ui-development
- patch: |-
    - op: replace
      path: /metadata/name
      value: myapp-ui-qa
  target:
    kind: RoleBinding
    name: myapp-ui-development
resources:
- ../base/main
- ../base/01-rolebindings
- ../base/02-rolebindings
images:
- name: image-registry.openshift-image-registry.svc:5000/myapp-ui-ci/myapp-ui-runtime
  newTag: b947-46j8x
