apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesJson6902:
- patch: |-
    - op: replace
      path: /metadata/namespace
      value: myapp-qa
  target:
    kind: Deployment
    name: myapp
- patch: |-
    - op: replace
      path: /metadata/namespace
      value: myapp-qa
  target:
    kind: Service
    name: myapp
- patch: |-
    - op: replace
      path: /metadata/namespace
      value: myapp-qa
  target:
    kind: Route
    name: myapp-route
- patch: |-
    - op: replace
      path: /metadata/name
      value: myapp-qa
  target:
    kind: Namespace
    name: myapp-development
- patch: |-
    - op: replace
      path: /metadata/namespace
      value: myapp-qa
  target:
    kind: RoleBinding
    name: argocd-admin
- patch: |-
    - op: replace
      path: /subjects/0/namespace
      value: myapp-qa
  target:
    kind: RoleBinding
    name: myapp-development
- patch: |-
    - op: replace
      path: /metadata/name
      value: myapp-qa
  target:
    kind: RoleBinding
    name: myapp-development
resources:
- ../base/main
- ../base/01-rolebindings
- ../base/02-rolebindings
images:
- name: image-registry.openshift-image-registry.svc:5000/myapp-ci/myapp-runtime
  newTag: 5cbf-m5l87
